# описания сервисов (контейнеров), которые должны быть развёрнуты
services:
  # описание контейнера db
  db: # имя сервиса
    # образ, из которого должен быть запущен контейнер
    image: postgres:16.1
    # имя, которое нужно присвоить контейнеру
    container_name: java-postgres
    # публикуемые порты
    ports:
      - "6432:5432"
    # настройки монтирования volume
    volumes:
      - catsgram-pgdata:/var/lib/postgresql/data/
      - ./temp:/temp
    # переменные окружения
    environment:
      - POSTGRES_DB=catsgram
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=catsgram
    # описание способа проверки, что контейнер в рабочем состоянии
    healthcheck:
      # указываем, какую команду выполнить внутри контейнера для проверки его статуса
      # в этом примере вызывается утилита pg_isready, входящая в состав PostgreSQL
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      # через какое время после запуска начинать проверку
      timeout: 5s
      # интервал повторов проверки
      interval: 5s
      # количество попыток
      retries: 10

volumes:
  catsgram-pgdata:
    external: true
